from codebase_graph_latex.repository_graph.sample_scatter_touched_against_commit import generate_and_save as scatter_sample_commit_knowledge_generate_and_save
from codebase_graph_latex.repository_graph.average_components_touched_by_developer import generate_and_save as repository_average_touched_generate_and_save
from codebase_graph_latex.repository_graph.repository_pull_request import generate_and_save as repository_pull_request_generate_and_save
from codebase_graph_latex.repository_graph.total_commits_by_developer import generate_and_save as developer_commit_generate_and_save
from codebase_graph_latex.repository_graph.histogram_components_touched_by_developer import generate_and_save as repository_histogram_commit_generate_and_save


def generate_and_save(number_of_repositories):
    scatter_sample_commit_knowledge_generate_and_save()
    developer_commit_generate_and_save(number_of_repositories)
    repository_histogram_commit_generate_and_save(number_of_repositories)
    repository_average_touched_generate_and_save(number_of_repositories)
    repository_pull_request_generate_and_save(0)
    